version: 1
validation: sovereign
default_denom: umvlt
accounts: 
- name: alice
  coins:
  - 1000000000umvlt
- name: bob
  coins:
  - 1000000000umvlt
- name: carol
  coins:
  - 1000000000umvlt
validators:
- name: alice
  bonded: 200000000umvlt